### ISSUE TITLE
Partner node to be themed according to design

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#992]
It currently looks like this http://dev.amani-zen-theme.peacegeeks.org/content/peacegeeks

https://projects.invisionapp.com/d/main#/console/4971962/107296725/preview

**Comment by limage** [comment]
Done! committed to Amani-zen-theme branch.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks Please review and comment...  Moving back to In Progress

![zen992](https://cloud.githubusercontent.com/assets/16202351/12457134/d33c196a-bf57-11e5-997a-2ebec973d4a3.jpg)

**Comment by erica-scott** [comment]
Added a few changes so that the node matches the mock more closely. Code needs to be pulled to dev.

A pull request has been made and merged into Amani-Zen-Theme.

**Comment by dannyzoujx** [comment]
I think we are still missing the carousel on this page http://dev.amani-zen-theme.peacegeeks.org/content/peacegeeks

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks I wonder what the complete page should be.  Programs are showing but we are missing the Map record and the Link fields.  Moving back to In Progress
![zen992a](https://cloud.githubusercontent.com/assets/16202351/14035550/e4ea4c0a-f1ec-11e5-8ffc-3a04e6df49ce.JPG)
![zen992b](https://cloud.githubusercontent.com/assets/16202351/14035551/e4eb3c32-f1ec-11e5-9f10-27fd19bc9370.JPG)

**Comment by erica-scott** [comment]
Added the map record and the website link to be displayed in the same way as the programs link. If another decision is made about how they are wanting this to be displayed, it will need to be reopened.

**Comment by MagdiRizkallah** [comment]
Verified on Dev
